export {
  addDomain,
  domainExistsPortal,
  domainExists,
  ensureUniqueDomainName,
  getDomainsForSite,
  getUniqueDomainNamePortal,
  getUniqueDomainName,
  isDomainForLegacySite,
  isDomainUsedElsewhere,
  isValidDomain,
  lookupDomain,
  removeDomain,
  updateDomain,
  IDomainEntry,
} from "@esri/hub-common";
