language: node_js
sudo: false
notifications:
  email: false
  slack:
    secure: "Hd3R65Uwp3h88z5761cRmHL93xdrOYSJJOqtiKHLKDCG4cnJfQOjdaDaR+dv1gXIs8kXnPlaDVmtmgEhaaPgmU1RJ/YvKmtkc5mbAYLZHr3z+rXK/MQzpLBEU9CqpXztpge+1k3Vec3+USOPodDKQ1wCX2rn2D+U7A/BeznwgUkaLj5Sv8YE0i8OxIbXTTLYFoAQYXChDe/ekrPXiGZVYdCjseBNbJt65yCBiFsPuqz0nMJ48eW45b3szbROigEzY1sAxd5b3UTlBX7b9olM1tvmQxELW5rxck4kLhoQCgoERMlkkLBmpop8nsmUFzaY3VrvayebI59M+AWe0SjaPRakghHOCJwtyw4ohEkdCzi1NYeZCGPRO98SpqxtppU7DvdzhzJZVeJrwBk5iqYrcBSFbVpBtngaiWAZ/NwSurFKhER2ZIuZHIcQ3kKJnL4OUUA3MOseMxE/7k5KIiRRAqnPYuqfcZFVYupGHaJdYXVPRwMzMJr4YUrrXfUTAEy1r35TuwDjN9B4X7iP3q8TSwN63DKRpymwqXwzu/ti/EEpIWkBPuChFK0SDAOxtJHBykTZFR/fyslzmkZSEQlj27rPr8MuoGoRNdFcqw/jJ+aBf1zJ6kCfwQlQLNG+ibhKrBmyT/gxg4YgEkh9FbUOGM4swfvONtvpxstbgdmjEns="
    on_success: change
    on_failure: always
node_js:
- '8'
- '10'
cache:
  directories:
  - node_modules
before_script:
- npm run bootstrap
script:
- npm run test:ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local-dir: docs/build
  target_branch: gh-pages
before_deploy:
- npm run docs:build
env:
- MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
