language: node_js
sudo: false
notifications:
  email: false
  slack:
    secure: 4zQtBJ3DuJL3IIbDsq+IR4i2iaL8yYiatECXb4zjcvxoqC7r0QCJ2lkvsyLjJT6vPNGIA3HB3HfV23cH5RxGHuD9ZXfaWo2UhYQ/hq0zhxGdzrujqNYkXEWAKstkpYY2o5Edtfg5rco3NxuEVVgptpptbTW4kM+BrutFltlWkR04056OUozmQnPOJy4hJ084FgR2fsMQdzqd/UmwEYnUt8JvfTC6UQolcyp48+w+0DeS1jyOr5LyttpVg2t+1Ap9QWsf4pR1zOWl8RD+zs9tGgEQIW7NswymxVE6AcTeMOwXN1Nh3NaDoLMsOrGHlcFQRmtPL6QOKctpZUXlKKP+ENpcWOj0sQrHqFe1cPWIZ4OulFJHhW9X3J6anoi9Z1lK1KeeMkw/LFdp745Tm/88ZsJ6uV3gjx9NsespowSK2YU4LOtFGsPp5jceQabl3xgs4FLGH03dnD7dmj+7lSQ6CgsUgjLVHjHCDnTvEVe4+eM3f78eQsjxvl5IP/mNJgcVuRnaL+kor0DV5EoshbzXlP3bqFG3QceUdQj46XIhb0+SCjwoclsJKfl3YsCKukMT5Y+27zJASzOufhWV+yhadOHijwZwwd2GUEU8JwcUmk5EoEcmxB8S3A5guRwY6ok9OTag36q8jAD4RMOJjyddsDVtLKF+KoZG2XFjbV+DnnQ=
node_js:
- '8'
- '10'
cache:
  directories:
  - node_modules
before_script:
- npm run bootstrap
script:
- npm run test:ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local-dir: docs/build
  target_branch: gh-pages
before_deploy:
- npm run docs:build
env:
- MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
branches:
  only:
    - master
