/**
 * Site Permissions
 * This feeds into the Permissions type
 */
export const SitePermissions = [
  "hub:site",
  "hub:site:create",
  "hub:site:delete",
  "hub:site:edit",
  "hub:site:view",
  "hub:site:owner",
  "hub:site:canChangeAccess",
  "hub:site:events",
  "hub:site:content",
  "hub:site:discussions",
  "hub:site:feature:follow",
  "hub:site:feature:discussions",
  "hub:site:workspace",
  "hub:site:workspace:overview",
  "hub:site:workspace:dashboard",
  "hub:site:workspace:details",
  "hub:site:workspace:settings",
  "hub:site:workspace:collaborators",
  "hub:site:workspace:catalog",
  "hub:site:workspace:catalog:content",
  "hub:site:workspace:catalog:events",
  "hub:site:workspace:catalog:upgrade",
  "hub:site:workspace:metrics",
  "hub:site:workspace:followers",
  "hub:site:workspace:followers:member",
  "hub:site:workspace:followers:manager",
  "hub:site:workspace:followers:create",
  "hub:site:workspace:pages",
  "hub:site:workspace:events",
  "hub:site:workspace:projects",
  "hub:site:workspace:initiatives",
  "hub:site:manage",
  "hub:site:workspace:feeds",
  "hub:site:workspace:assistant",
  "hub:site:workspace:settings:discussions",
  "hub:site:assistant:access",
] as const;
