// migrated from:
// https://github.com/Esri/hub.js/blob/7ba3f21b987d2d1d6cee30a34067d53fb1f22e68/.eslintrc.js
import { defineConfig, globalIgnores } from "eslint/config";

import js from "@eslint/js";
import tseslint from "typescript-eslint";

import { FlatCompat } from "@eslint/eslintrc";

const __dirname = import.meta.dirname;

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

export default defineConfig([
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    languageOptions: {
      // parser: tsParser,
      sourceType: "module",
      ecmaVersion: 2020,

      parserOptions: {
        tsconfigRootDir: __dirname,
        project: ["./tsconfig.json"],
      },
    },

    rules: {
      // Add custom rules here
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-empty-function": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/explicit-function-return-type": "warn",
      "@typescript-eslint/no-explicit-any": "warn",
      "no-unused-vars": "off", // use the TS version instead

      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_", // Ignore unused arguments prefixed with '_'
          caughtErrorsIgnorePattern: "^_", // Ignore unused catch clause errors prefixed with '_'
        },
      ],

      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@esri/arcgis-rest-portal",
              importNames: ["createItem", "updateItem", "commitItemUpload"],
              message:
                "Do not import createItem, updateItem or commitItemUpload from @esri/arcgis-rest-portal. Use the wrapper functions of the same name from @esri/hub-common.",
            },
          ],
          patterns: [
            {
              group: ["**/dist/**"],
              message: "Importing from a 'dist' directory is not allowed.",
            },
          ],
        },
      ],

      "no-restricted-syntax": [
        "error",
        {
          selector:
            'ExportNamedDeclaration[source] :not([parent.id.name="index.ts"])', // Named exports with a source (re-exports)
          message: "Re-exports are only allowed from the root index.ts file.",
        },
        {
          selector: 'ExportAllDeclaration :not([parent.id.name="index.ts"])', // All exports (re-exports)
          message: "Re-exports are only allowed from the root index.ts file.",
        },
        {
          selector: "TSEnumDeclaration", // Enum declarations
          message:
            "Enums are not allowed. Consider using separate const and type. E.g. const FRUIT = { APPLE: 'apple', BANANA: 'banana' } as const; type Fruit = typeof FRUIT[keyof typeof FRUIT];",
        },
        {
          selector: "ImportExpression",
          message: "Dynamic import() is not allowed.",
        },
      ],

      "@typescript-eslint/no-require-imports": "error",
    },
  },
  {
    files: ["**/*.{test,spec}.ts"], // Files for tests

    rules: {
      // Rules specific for test files
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/require-await": "off",
      "no-unused-vars": "off",
      "no-console": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "no-restricted-imports": [
        "error",
        {
          // namespaced import statements (i.e. `import * as something from `@esri/arcgis-rest-portal`;) get flagged as
          // importing restricted `createItem`, `updateItem` and `commitItemUpload` methods in test modules.
          // below rule turns that off in test modules only.
          paths: [],
          patterns: [
            {
              group: ["**/dist/**"],
              message: "Importing from a 'dist' directory is not allowed.",
            },
          ],
        },
      ],
    },
  },
  {
    // only the root barrel file is allowed to have re-export statements
    files: ["src/index.ts"],

    rules: {
      "no-restricted-syntax": "off",
    },
  },
  {
    // files that are auto-generated by orval
    files: [
      "src/events/api/**/*.ts",
      "src/newsletters/api/**/*.ts",
      "src/newsletters-scheduler/api/**/*.ts",
    ],

    rules: {
      // ignore re-export statements and enums in auto-generated code
      "no-restricted-syntax": "off",
      // ignore errors caused by not auto-generated code not calling `.toString()` on `URLSearchParams` objects
      "@typescript-eslint/restrict-template-expressions": "off",
    },
  },
  {
    files: [
      // existing enums. please do not add additional enums; they cause tree-shaking issues
      // due to the nature in how they are transpiled to IIFEs and results in unused bytes
      // being bundled by client libraries and applications. A better alternative to enums
      // is to define a separate const and type.
      // e.g.
      //   const FRUIT = { APPLE: 'Apple', BANANA: 'Banana' } as const;
      //   type Fruit = typeof FRUIT[keyof typeof FRUIT]; // union type of enum values
      //   const fruit: Fruit = FRUIT.APPLE;
      //
      // we will be removing the below enums in the future to reduce our bundle sizes
      "src/content/_internal/enums/datePrecision.ts",
      "src/content/enums/jobRecordStatus.ts",
      "src/content/enums/jobRecordType.ts",
      "src/content/enums/serviceCapabilities.ts",
      "src/content/enums/updateFrequency.ts",
      "src/core/enums/embedKind.ts",
      "src/core/enums/expressionRelationships.ts",
      "src/core/enums/featureLayerStyle.ts",
      "src/core/enums/metricVisibility.ts",
      "src/core/enums/publisherSource.ts",
      "src/core/enums/timelineStageStatuses.ts",
      "src/core/enums/uiSchemaElementTypes.ts",
      "src/core/enums/uiSchemaMessageTypes.ts",
      "src/core/enums/uiSchemaRuleEffects.ts",
      "src/core/enums/uiSchemaSectionTypes.ts",
      "src/core/schemas/internal/metrics/enums/icons.ts",
      "src/core/schemas/internal/metrics/enums/layouts.ts",
      "src/core/schemas/internal/metrics/enums/scale.ts",
      "src/core/schemas/internal/metrics/enums/source.ts",
      "src/core/schemas/internal/metrics/enums/unitPositions.ts",
      "src/core/schemas/internal/metrics/enums/visualInterest.ts",
      "src/core/schemas/shared/enums/alignments.ts",
      "src/core/schemas/shared/enums/cardTitleTags.ts",
      "src/core/schemas/shared/enums/corners.ts",
      "src/core/schemas/shared/enums/dropShadows.ts",
      "src/discussions/api/enums/aclCategory.ts",
      "src/discussions/api/enums/aclSubCategory.ts",
      "src/discussions/api/enums/channelFilter.ts",
      "src/discussions/api/enums/channelRelation.ts",
      "src/discussions/api/enums/channelSort.ts",
      "src/discussions/api/enums/commonSort.ts",
      "src/discussions/api/enums/discussionSource.ts",
      "src/discussions/api/enums/discussionType.ts",
      "src/discussions/api/enums/entitySettingsType.ts",
      "src/discussions/api/enums/postReaction.ts",
      "src/discussions/api/enums/postRelation.ts",
      "src/discussions/api/enums/postSort.ts",
      "src/discussions/api/enums/postStatus.ts",
      "src/discussions/api/enums/postType.ts",
      "src/discussions/api/enums/reactionRelation.ts",
      "src/discussions/api/enums/role.ts",
      "src/discussions/api/enums/searchPostsFormat.ts",
      "src/discussions/api/enums/sharingAccess.ts",
      "src/discussions/api/enums/sortOrder.ts",
      "src/downloads/enums/downloadOperationStatus.ts",
      "src/downloads/enums/serviceDownloadFormat.ts",
      "src/enums/fileExtension.ts",
      "src/enums/hubEntityHero.ts",
      "src/enums/hubEntityStatus.ts",
      "src/enums/itemType.ts",
      "src/events/enums/hubEventAttendanceType.ts",
      "src/events/enums/hubEventCapacityType.ts",
      "src/sites/_internal/enums/searchCategories.ts",
    ],

    rules: {
      "no-restricted-syntax": "off",
    },
  },
  {
    files: ["src/rest/portal/wrappers.ts"],

    rules: {
      "no-restricted-imports": [
        "error",
        {
          // ignores imports of `createItem`, `updateItem` and `commitItemUpload` from `@esri/arcgis-rest-portal` in the wrapper module
          paths: [],
          patterns: [
            {
              group: ["**/dist/**"],
              message: "Importing from a 'dist' directory is not allowed.",
            },
          ],
        },
      ],
    },
  },
  globalIgnores([
    "**/node_modules",
    "packages/**/dist",
    "packages/**/node_modules",
    "**/coverage",
    "**/docs",
    "**/commitlint.config.js",
    "**/exit-if-no-staged.js",
    "templates/*",
    "**/scripts",
    "**/support",
    "*/e2e/*",
    "**/archive",
  ]),
]);
