const { clear } = require('console');

    /** @type {import('ts-jest').JestConfigWithTsJest} */
    module.exports = {
      // needed b/c we ported the tests over from jasmine
      clearMocks: true,
      preset: 'ts-jest',
      testEnvironment: 'jsdom', // or 'jsdom' for browser environments
      testPathIgnorePatterns: [
        // default
        "/node_modules/",
        // the codemod flagged this file w/ the following error:
        // Unsupported Jasmine functionality "jasmine.createSpy().and.returnValues".
        // on lines 34, 56, 91, 11, 153, 190, 227, 264
        "/test/utils/poll.test.ts$",
        // the following files need to use jest.mock() for REST JS modules:
        "test/associations/internal/getIncludesAndReferencesQuery.test.ts",
        "test/associations/internal/getIncludesDoesNotReferenceQuery.test.ts",
        "test/associations/internal/getReferencesDoesNotIncludeQuery.test.ts",
        "test/associations/breakAssociation.test.ts",
        "test/associations/requestAssociation.test.ts",
        "test/content/content.test.ts",
        "test/content/edit.test.ts",
        "test/content/fetchContent.test.ts",
        "test/content/HubContent.test.ts",
        "test/core/_internal/sharedWith.test.ts",
        "test/core/schemas/internal/fetchCategoryItems.test.ts",
        "test/core/schemas/internal/getTagItems.test.ts",
        "test/core/enrichEntity.test.ts",
        "test/core/EntityEditor.test.ts",
        "test/core/HubItemEntity.test.ts",
        "test/core/setEntityAccess.test.ts",
        "test/discussions/edit.test.ts",
        "test/discussions/fetch.test.ts",
        "test/discussions/HubDiscussion.test.ts",
        "test/discussions/utils.test.ts",
        "test/downloads/_internal/file-url-fetchers/fetchExportImageDownloadFile.test.ts",
        "test/events/_internal/buildEventAssociations.test.ts",
        "test/events/_internal/EventUiSchemaAttendeesSettings.test.ts",
        "test/events/_internal/EventUiSchemaCreate.test.ts",
        "test/events/_internal/EventUiSchemaEdit.test.ts",
        "test/events/_internal/shareEventWithGroups.test.ts",
        "test/events/_internal/unshareEventWithGroups.test.ts",
        "test/events/edit.test.ts",
        "test/events/fetch.test.ts",
        "test/events/getEventGroups.test.ts",
        "test/events/HubEvent.test.ts",
        "test/extent/get-geographic-org-extent.test.ts",
        "test/groups/_internal/autoAddUsersAsAdmin.test.ts",
        "test/groups/_internal/convertGroupToHubGroup.test.ts",
        "test/groups/_internal/enrichments.test.ts",
        "test/groups/add-users-workflow/output-processors/_process-primary-email.test.ts",
        "test/groups/add-users-workflow/output-processors/_process-secondary-email.test.ts",
        "test/groups/_unprotect-and-remove-group.test.ts",
        "test/groups/autoAddUsers.test.ts",
        "test/groups/deleteGroupThumbnail.test.ts",
        "test/groups/emailOrgUsers.test.ts",
        "test/groups/HubGroup.test.ts",
        "test/groups/HubGroups.test.ts",
        "test/groups/inviteUsers.test.ts",
        "test/groups/setGroupThumbnail.test.ts",
        "test/initiative-templates/edit.test.ts",
        "test/initiative-templates/fetch.test.ts",
        "test/initiative-templates/HubInitiativeTemplate.test.ts",
        "test/initiatives/HubInitiative.test.ts",
        "test/initiatives/HubInitiatives.test.ts",
        "test/items/_unprotect-and-remove-item.test.ts",
        "test/items/_wait-for-item-ready.test.ts",
        "test/items/create-item-from-file.test.ts",
        "test/items/create-item-from-url-or-file.test.ts",
        "test/items/deleteItemThumbnail.test.ts",
        "test/items/does-item-exist-with-title.test.ts",
        "test/items/fetch-all-pages.test.ts",
        "test/items/fetch.test.ts",
        "test/items/follow.test.ts",
        "test/items/is-services-directory-disabled.test.ts",
        "test/items/registerBrowserApp.test.ts",
        "test/items/share-item-to-groups.test.ts",
        "test/items/slugs.test.ts",
        "test/items/unprotect-model.test.ts",
        "test/items/unshare-item-from-groups.test.ts",
        "test/items/uploadImageResource.test.ts",
        "test/metrics/resolveMetric.test.ts",
        "test/models/models.test.ts",
        "test/org/fetch-org.test.ts",
        "test/org/fetchOrgLimits.test.ts",
        "test/pages/HubPage.test.ts",
        "test/pages/HubPages.test.ts",
        "test/projects/edit.test.ts",
        "test/projects/fetch.test.ts",
        "test/projects/HubProject.test.ts",
        "test/resources/fetch-and-upload-resource.test.ts",
        "test/resources/get-item-assets.test.ts",
        "test/resources/removeResource.test.ts",
        "test/resources/upsertResource.test.ts",
        "test/search/_internal/hubDiscussionsHelpers/channelResultsToSearchResults.test.ts",
        "test/search/_internal/hubEventsHelpers/eventAttendeeToSearchResult.test.ts",
        "test/search/_internal/hubEventsHelpers/eventToSearchResult.test.ts",
        "test/search/_internal/hubEventsHelpers/processFilters.test.ts",
        "test/search/_internal/explainHelpers.test.ts",
        "test/search/_internal/portalSearchGroupMembers.test.ts",
        "test/search/_internal/portalSearchGroups.test.ts",
        "test/search/_internal/portalSearchItems.test.ts",
        "test/search/_internal/portalSearchUsers.test.ts",
        "test/search/fetchEntityCatalog.test.ts",
        "test/sites/domains/_lookup-portal.test.ts",
        "test/sites/HubSite.test.ts",
        "test/sites/HubSites.test.ts",
        "test/sites/registerBrowserApp.test.ts",
        "test/surveys/utils/get-form-info-json.test.ts",
        "test/surveys/utils/get-form-json.test.ts",
        "test/surveys/utils/get-input-feature-service-model.test.ts",
        "test/surveys/utils/get-source-feature-service-model-from-fieldworker.test.ts",
        "test/surveys/utils/get-stakeholder-model.test.ts",
        "test/surveys/utils/get-survey-models.test.ts",
        "test/surveys/edit.test.ts",
        "test/surveys/fetch.test.ts",
        "test/surveys/HubSurvey.test.ts",
        "test/templates/edit.test.ts",
        "test/templates/fetch.test.ts",
        "test/urls/get-portal-url.test.ts",
        "test/users/_internal/computeProps.test.ts",
        "test/users/_internal/enrichments.test.ts",
        "test/users/_internal/UserUiSchemaSettings.test.ts",
        "test/users/HubUser.test.ts",
        "test/users/HubUsers.test.ts",
        "test/utils/internal/resolveItemQueryValues.test.ts",
        "test/utils/internal/resolvePortalValues.test.ts",
        "test/utils/internal/resolveServiceQueryValues.test.ts",
        "test/utils/internal/updateCommunityOrgSettings.test.ts",
        "test/utils/internal/updatePortalOrgSettings.test.ts",
        "test/utils/internal/userAppResources.test.ts",
        "test/versioning/createVersion.test.ts",
        "test/versioning/deleteVersion.test.ts",
        "test/versioning/getVersion.test.ts",
        "test/versioning/searchVersions.test.ts",
        "test/versioning/updateVersion.test.ts",
        "test/versioning/updateVersionMetadata.test.ts",
        "test/ArcGISContextManager.test.ts",
      ],
    };
    