import { defineConfig } from "vite";
import { coverageConfigDefaults } from 'vitest/config';

export default defineConfig({
  test: {
    // allow tests to use globals like describe/it/expect without importing them
    // to make it easier to convert jasmine/karma tests which also use globals
    globals: true,
    include: [
      // we use .spec.ts for vitest and .test.ts for karma/jasmine
      "test/**/*.spec.ts"
    ],
    coverage: {
      enabled: true,
      include: [
        "src/**/*.ts"
      ],
      exclude: [
        ...coverageConfigDefaults.exclude,
        // files that were generated by orval
        "src/**/orval/**/*.ts",
      ],
      // we have so many pre-existing istanbul ignore comments
      provider: "istanbul",
      // reporter: ["json", "html", "cobertura"],
      reportsDirectory: "./coverage",
      thresholds: {
        100: true
      }
    },
    // threads seem to be ~33% faster than forks so we use them by default
    // if this causes issues in CI, we can use --pool=forks there
    // https://vitest.dev/guide/improving-performance.html#pool
    pool: "threads"
  }
});
