export type {
  FieldType,
  IItem,
  IGroup,
  IUser,
  IExtent,
  IPagingParams,
  IPagedResponse,
  IPoint,
  IPolygon,
  Position,
  IGeometry,
  ISpatialReference,
  ILayerDefinition,
  IFeatureServiceDefinition,
  IItemAdd,
  IStatisticDefinition,
  IField,
} from "@esri/arcgis-rest-types";
