/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ArcgisHubLogin {
      'clientid': string;
      'communityorg': string;
      'enterpriseorg': string;
      'session': string;
    }
  }

  interface HTMLArcgisHubLoginElement extends StencilComponents.ArcgisHubLogin, HTMLStencilElement {}

  var HTMLArcgisHubLoginElement: {
    prototype: HTMLArcgisHubLoginElement;
    new (): HTMLArcgisHubLoginElement;
  };
  interface HTMLElementTagNameMap {
    'arcgis-hub-login': HTMLArcgisHubLoginElement;
  }
  interface ElementTagNameMap {
    'arcgis-hub-login': HTMLArcgisHubLoginElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'arcgis-hub-login': JSXElements.ArcgisHubLoginAttributes;
    }
  }
  namespace JSXElements {
    export interface ArcgisHubLoginAttributes extends HTMLAttributes {
      'clientid'?: string;
      'communityorg'?: string;
      'enterpriseorg'?: string;
      'onEventFoo'?: (event: CustomEvent) => void;
      'session'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
