import { IPermissionPolicy } from "./types/IPermissionPolicy";

/**
 * Platform Permission policies which delegate to Platform Privileges
 */
export const PlatformPermissionPolicies: IPermissionPolicy[] = [
  {
    permission: "platform:features:user:edit",
    services: ["portal"],
    authenticated: true,
    privileges: ["features:user:edit"],
  },
  {
    permission: "platform:features:user:fullEdit",
    services: ["portal"],
    authenticated: true,
    privileges: ["features:user:fullEdit"],
  },
  {
    permission: "platform:features:user:manageVersions",
    services: ["portal"],
    authenticated: true,
    privileges: ["features:user:manageVersions"],
  },
  {
    permission: "platform:marketplace:admin:manage",
    services: ["portal"],
    authenticated: true,
    privileges: ["marketplace:admin:manage"],
  },
  {
    permission: "platform:marketplace:admin:purchase",
    services: ["portal"],
    authenticated: true,
    privileges: ["marketplace:admin:purchase"],
  },
  {
    permission: "platform:marketplace:admin:startTrial",
    services: ["portal"],
    authenticated: true,
    privileges: ["marketplace:admin:startTrial"],
  },
  {
    permission: "platform:opendata:user:designateGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["opendata:user:designateGroup"],
  },
  {
    permission: "platform:opendata:user:openDataAdmin",
    services: ["portal"],
    authenticated: true,
    privileges: ["opendata:user:openDataAdmin"],
  },
  {
    permission: "platform:portal:admin:assignToGroups",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:assignToGroups"],
  },
  {
    permission: "platform:portal:admin:categorizeItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:categorizeItems"],
  },
  {
    permission: "platform:portal:admin:changeUserRoles",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:changeUserRoles"],
  },
  {
    permission: "platform:portal:admin:createGPWebhook",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:createGPWebhook"],
  },
  {
    permission: "platform:portal:admin:createUpdateCapableGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:createUpdateCapableGroup"],
  },
  {
    permission: "platform:portal:admin:createLeavingDisallowedGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:createLeavingDisallowedGroup"],
  },
  {
    permission: "platform:portal:admin:deleteGroups",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:deleteGroups"],
  },
  {
    permission: "platform:portal:admin:deleteItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:deleteItems"],
  },
  {
    permission: "platform:portal:admin:deleteUsers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:deleteUsers"],
  },
  {
    permission: "platform:portal:admin:disableUsers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:disableUsers"],
  },
  {
    permission: "platform:portal:admin:inviteUsers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:inviteUsers"],
  },
  {
    permission: "platform:portal:admin:manageCollaborations",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageCollaborations"],
  },
  {
    permission: "platform:portal:admin:manageCredits",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageCredits"],
  },
  {
    permission: "platform:portal:admin:manageEnterpriseGroups",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageEnterpriseGroups"],
  },
  {
    permission: "platform:portal:admin:manageLicenses",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageLicenses"],
  },
  {
    permission: "platform:portal:admin:manageRoles",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageRoles"],
  },
  {
    permission: "platform:portal:admin:manageSecurity",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageSecurity"],
  },
  {
    permission: "platform:portal:admin:manageServers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageServers"],
  },
  {
    permission: "platform:portal:admin:manageUtilityServices",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageUtilityServices"],
  },
  {
    permission: "platform:portal:admin:manageWebhooks",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageWebhooks"],
  },
  {
    permission: "platform:portal:admin:manageWebsite",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:manageWebsite"],
  },
  {
    permission: "platform:portal:admin:reassignGroups",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:reassignGroups"],
  },
  {
    permission: "platform:portal:admin:reassignItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:reassignItems"],
  },
  {
    permission: "platform:portal:admin:reassignUsers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:reassignUsers"],
  },
  {
    permission: "platform:portal:admin:shareToGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:shareToGroup"],
  },
  {
    permission: "platform:portal:admin:shareToOrg",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:shareToOrg"],
  },
  {
    permission: "platform:portal:admin:shareToPublic",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:shareToPublic"],
  },
  {
    permission: "platform:portal:admin:updateGroups",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:updateGroups"],
  },
  {
    permission: "platform:portal:admin:updateItemCategorySchema",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:updateItemCategorySchema"],
  },
  {
    permission: "platform:portal:admin:updateItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:updateItems"],
  },
  {
    permission: "platform:portal:admin:updateMemberCategorySchema",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:updateMemberCategorySchema"],
  },
  {
    permission: "platform:portal:admin:updateUsers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:updateUsers"],
  },
  {
    permission: "platform:portal:admin:viewGroups",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:viewGroups"],
  },
  {
    permission: "platform:portal:admin:viewItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:viewItems"],
  },
  {
    permission: "platform:portal:admin:viewUsers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:admin:viewUsers"],
  },
  {
    permission: "platform:portal:publisher:bulkPublishFromDataStores",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:bulkPublishFromDataStores"],
  },
  {
    permission: "platform:portal:publisher:createDataPipelines",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:createDataPipelines"],
  },
  {
    permission: "platform:portal:publisher:createFeatureWebhook",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:createFeatureWebhook"],
  },
  {
    permission: "platform:portal:publisher:publishBigDataAnalytics",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishBigDataAnalytics"],
  },
  {
    permission: "platform:portal:publisher:publishDynamicImagery",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishDynamicImagery"],
  },
  {
    permission: "platform:portal:publisher:publishFeatures",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishFeatures"],
  },
  {
    permission: "platform:portal:publisher:publishFeeds",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishFeeds"],
  },
  {
    permission: "platform:portal:publisher:publishKnowledgeGraph",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishKnowledgeGraph"],
  },
  {
    permission: "platform:portal:publisher:publishRealTimeAnalytics",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishRealTimeAnalytics"],
  },
  {
    permission: "platform:portal:publisher:publishScenes",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishScenes"],
  },
  {
    permission: "platform:portal:publisher:publishServerGPServices",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishServerGPServices"],
  },
  {
    permission: "platform:portal:publisher:publishServerServices",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishServerServices"],
  },
  {
    permission: "platform:portal:publisher:publishTiledImagery",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishTiledImagery"],
  },
  {
    permission: "platform:portal:publisher:publishTiles",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:publishTiles"],
  },
  {
    permission: "platform:portal:publisher:registerDataStores",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:publisher:registerDataStores"],
  },
  {
    permission: "platform:portal:user:addExternalMembersToGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:addExternalMembersToGroup"],
  },
  {
    permission: "platform:portal:user:categorizeItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:categorizeItems"],
  },
  {
    permission: "platform:portal:user:createGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:createGroup"],
  },
  {
    permission: "platform:portal:user:createItem",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:createItem"],
  },
  {
    permission: "platform:portal:user:invitePartneredCollaborationMembers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:invitePartneredCollaborationMembers"],
  },
  {
    permission: "platform:portal:user:joinGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:joinGroup"],
  },
  {
    permission: "platform:portal:user:joinNonOrgGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:joinNonOrgGroup"],
  },
  {
    permission: "platform:portal:user:reassignItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:reassignItems"],
  },
  {
    permission: "platform:portal:user:receiveItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:receiveItems"],
  },
  {
    permission: "platform:portal:user:runWebTool",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:runWebTool"],
  },
  {
    permission: "platform:portal:user:shareGroupToOrg",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:shareGroupToOrg"],
  },
  {
    permission: "platform:portal:user:shareGroupToPublic",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:shareGroupToPublic"],
  },
  {
    permission: "platform:portal:user:shareToGroup",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:shareToGroup"],
  },
  {
    permission: "platform:portal:user:shareToOrg",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:shareToOrg"],
  },
  {
    permission: "platform:portal:user:shareToPublic",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:shareToPublic"],
  },
  {
    permission: "platform:portal:user:viewHostedFeatureServices",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:viewHostedFeatureServices"],
  },
  {
    permission: "platform:portal:user:viewHostedTileServices",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:viewHostedTileServices"],
  },
  {
    permission: "platform:portal:user:viewOrgGroups",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:viewOrgGroups"],
  },
  {
    permission: "platform:portal:user:viewOrgItems",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:viewOrgItems"],
  },
  {
    permission: "platform:portal:user:viewOrgUsers",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:viewOrgUsers"],
  },
  {
    permission: "platform:portal:user:viewTracks",
    services: ["portal"],
    authenticated: true,
    privileges: ["portal:user:viewTracks"],
  },
  {
    permission: "platform:premium:publisher:createAdvancedNotebooks",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:publisher:createAdvancedNotebooks"],
  },
  {
    permission: "platform:premium:publisher:createNotebooks",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:publisher:createNotebooks"],
  },
  {
    permission: "platform:premium:publisher:geoanalytics",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:publisher:geoanalytics"],
  },
  {
    permission: "platform:premium:publisher:rasteranalysis",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:publisher:rasteranalysis"],
  },
  {
    permission: "platform:premium:publisher:scheduleNotebooks",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:publisher:scheduleNotebooks"],
  },
  {
    permission: "platform:premium:user:demographics",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:demographics"],
  },
  {
    permission: "platform:premium:user:elevation",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:elevation"],
  },
  {
    permission: "platform:premium:user:featurereport",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:featurereport"],
  },
  {
    permission: "platform:premium:user:geocode:stored",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:geocode:stored"],
  },
  {
    permission: "platform:premium:user:geocode:temporary",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:geocode:temporary"],
  },
  {
    permission: "platform:premium:user:geocode",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:geocode"],
  },
  {
    permission: "platform:premium:user:geoenrichment",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:geoenrichment"],
  },
  {
    permission: "platform:premium:user:networkanalysis:closestfacility",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:closestfacility"],
  },
  {
    permission: "platform:premium:user:networkanalysis:locationallocation",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:locationallocation"],
  },
  {
    permission: "platform:premium:user:networkanalysis:optimizedrouting",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:optimizedrouting"],
  },
  {
    permission:
      "platform:premium:user:networkanalysis:origindestinationcostmatrix",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:origindestinationcostmatrix"],
  },
  {
    permission: "platform:premium:user:networkanalysis:routing",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:routing"],
  },
  {
    permission: "platform:premium:user:networkanalysis:servicearea",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:servicearea"],
  },
  {
    permission: "platform:premium:user:networkanalysis:vehiclerouting",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:vehiclerouting"],
  },
  {
    permission: "platform:premium:user:networkanalysis",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis"],
  },
  {
    permission: "platform:premium:user:places",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:places"],
  },
  {
    permission: "platform:premium:user:spatialanalysis",
    services: ["portal"],
    authenticated: true,
    privileges: ["premium:user:spatialanalysis"],
  },
];
