import { IPermissionPolicy } from "./types/IPermissionPolicy";

/**
 * All the permission policies for the Hub
 */
export const PlatformPermissions = [
  "platform:features:user:edit",
  "platform:features:user:fullEdit",
  "platform:features:user:manageVersions",
  "platform:marketplace:admin:manage",
  "platform:marketplace:admin:purchase",
  "platform:marketplace:admin:startTrial",
  "platform:opendata:user:designateGroup",
  "platform:opendata:user:openDataAdmin",
  "platform:portal:admin:assignToGroups",
  "platform:portal:admin:categorizeItems",
  "platform:portal:admin:changeUserRoles",
  "platform:portal:admin:createGPWebhook",
  "platform:portal:admin:createUpdateCapableGroup",
  "platform:portal:admin:deleteGroups",
  "platform:portal:admin:deleteItems",
  "platform:portal:admin:deleteUsers",
  "platform:portal:admin:disableUsers",
  "platform:portal:admin:inviteUsers",
  "platform:portal:admin:manageCollaborations",
  "platform:portal:admin:manageCredits",
  "platform:portal:admin:manageEnterpriseGroups",
  "platform:portal:admin:manageLicenses",
  "platform:portal:admin:manageRoles",
  "platform:portal:admin:manageSecurity",
  "platform:portal:admin:manageServers",
  "platform:portal:admin:manageUtilityServices",
  "platform:portal:admin:manageWebhooks",
  "platform:portal:admin:manageWebsite",
  "platform:portal:admin:reassignGroups",
  "platform:portal:admin:reassignItems",
  "platform:portal:admin:reassignUsers",
  "platform:portal:admin:shareToGroup",
  "platform:portal:admin:shareToOrg",
  "platform:portal:admin:shareToPublic",
  "platform:portal:admin:updateGroups",
  "platform:portal:admin:updateItemCategorySchema",
  "platform:portal:admin:updateItems",
  "platform:portal:admin:updateMemberCategorySchema",
  "platform:portal:admin:updateUsers",
  "platform:portal:admin:viewGroups",
  "platform:portal:admin:viewItems",
  "platform:portal:admin:viewUsers",
  "platform:portal:publisher:bulkPublishFromDataStores",
  "platform:portal:publisher:createDataPipelines",
  "platform:portal:publisher:createFeatureWebhook",
  "platform:portal:publisher:publishBigDataAnalytics",
  "platform:portal:publisher:publishDynamicImagery",
  "platform:portal:publisher:publishFeatures",
  "platform:portal:publisher:publishFeeds",
  "platform:portal:publisher:publishKnowledgeGraph",
  "platform:portal:publisher:publishRealTimeAnalytics",
  "platform:portal:publisher:publishScenes",
  "platform:portal:publisher:publishServerGPServices",
  "platform:portal:publisher:publishServerServices",
  "platform:portal:publisher:publishTiledImagery",
  "platform:portal:publisher:publishTiles",
  "platform:portal:publisher:registerDataStores",
  "platform:portal:user:addExternalMembersToGroup",
  "platform:portal:user:categorizeItems",
  "platform:portal:user:createGroup",
  "platform:portal:user:createItem",
  "platform:portal:user:invitePartneredCollaborationMembers",
  "platform:portal:user:joinGroup",
  "platform:portal:user:joinNonOrgGroup",
  "platform:portal:user:reassignItems",
  "platform:portal:user:receiveItems",
  "platform:portal:user:runWebTool",
  "platform:portal:user:shareGroupToOrg",
  "platform:portal:user:shareGroupToPublic",
  "platform:portal:user:shareToGroup",
  "platform:portal:user:shareToOrg",
  "platform:portal:user:shareToPublic",
  "platform:portal:user:viewHostedFeatureServices",
  "platform:portal:user:viewHostedTileServices",
  "platform:portal:user:viewOrgGroups",
  "platform:portal:user:viewOrgItems",
  "platform:portal:user:viewOrgUsers",
  "platform:portal:user:viewTracks",
  "platform:premium:publisher:createAdvancedNotebooks",
  "platform:premium:publisher:createNotebooks",
  "platform:premium:publisher:geoanalytics",
  "platform:premium:publisher:rasteranalysis",
  "platform:premium:publisher:scheduleNotebooks",
  "platform:premium:user:demographics",
  "platform:premium:user:elevation",
  "platform:premium:user:featurereport",
  "platform:premium:user:geocode:stored",
  "platform:premium:user:geocode:temporary",
  "platform:premium:user:geocode",
  "platform:premium:user:geoenrichment",
  "platform:premium:user:networkanalysis:closestfacility",
  "platform:premium:user:networkanalysis:locationallocation",
  "platform:premium:user:networkanalysis:optimizedrouting",
  "platform:premium:user:networkanalysis:origindestinationcostmatrix",
  "platform:premium:user:networkanalysis:routing",
  "platform:premium:user:networkanalysis:servicearea",
  "platform:premium:user:networkanalysis:vehiclerouting",
  "platform:premium:user:networkanalysis",
  "platform:premium:user:places",
  "platform:premium:user:spatialanalysis",
];

/**
 * Platform Permission policies which delegate to Platform Privileges
 */
export const PlatformPermissionPolicies: IPermissionPolicy[] = [
  {
    permission: "platform:features:user:edit",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["features:user:edit"],
  },
  {
    permission: "platform:features:user:fullEdit",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["features:user:fullEdit"],
  },
  {
    permission: "platform:features:user:manageVersions",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["features:user:manageVersions"],
  },
  {
    permission: "platform:marketplace:admin:manage",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["marketplace:admin:manage"],
  },
  {
    permission: "platform:marketplace:admin:purchase",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["marketplace:admin:purchase"],
  },
  {
    permission: "platform:marketplace:admin:startTrial",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["marketplace:admin:startTrial"],
  },
  {
    permission: "platform:opendata:user:designateGroup",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["opendata:user:designateGroup"],
  },
  {
    permission: "platform:opendata:user:openDataAdmin",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["opendata:user:openDataAdmin"],
  },
  {
    permission: "platform:portal:admin:assignToGroups",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:assignToGroups"],
  },
  {
    permission: "platform:portal:admin:categorizeItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:categorizeItems"],
  },
  {
    permission: "platform:portal:admin:changeUserRoles",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:changeUserRoles"],
  },
  {
    permission: "platform:portal:admin:createGPWebhook",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:createGPWebhook"],
  },
  {
    permission: "platform:portal:admin:createUpdateCapableGroup",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:createUpdateCapableGroup"],
  },
  {
    permission: "platform:portal:admin:deleteGroups",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:deleteGroups"],
  },
  {
    permission: "platform:portal:admin:deleteItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:deleteItems"],
  },
  {
    permission: "platform:portal:admin:deleteUsers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:deleteUsers"],
  },
  {
    permission: "platform:portal:admin:disableUsers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:disableUsers"],
  },
  {
    permission: "platform:portal:admin:inviteUsers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:inviteUsers"],
  },
  {
    permission: "platform:portal:admin:manageCollaborations",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageCollaborations"],
  },
  {
    permission: "platform:portal:admin:manageCredits",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageCredits"],
  },
  {
    permission: "platform:portal:admin:manageEnterpriseGroups",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageEnterpriseGroups"],
  },
  {
    permission: "platform:portal:admin:manageLicenses",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageLicenses"],
  },
  {
    permission: "platform:portal:admin:manageRoles",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageRoles"],
  },
  {
    permission: "platform:portal:admin:manageSecurity",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageSecurity"],
  },
  {
    permission: "platform:portal:admin:manageServers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageServers"],
  },
  {
    permission: "platform:portal:admin:manageUtilityServices",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageUtilityServices"],
  },
  {
    permission: "platform:portal:admin:manageWebhooks",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageWebhooks"],
  },
  {
    permission: "platform:portal:admin:manageWebsite",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:manageWebsite"],
  },
  {
    permission: "platform:portal:admin:reassignGroups",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:reassignGroups"],
  },
  {
    permission: "platform:portal:admin:reassignItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:reassignItems"],
  },
  {
    permission: "platform:portal:admin:reassignUsers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:reassignUsers"],
  },
  {
    permission: "platform:portal:admin:shareToGroup",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:shareToGroup"],
  },
  {
    permission: "platform:portal:admin:shareToOrg",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:shareToOrg"],
  },
  {
    permission: "platform:portal:admin:shareToPublic",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:shareToPublic"],
  },
  {
    permission: "platform:portal:admin:updateGroups",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:updateGroups"],
  },
  {
    permission: "platform:portal:admin:updateItemCategorySchema",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:updateItemCategorySchema"],
  },
  {
    permission: "platform:portal:admin:updateItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:updateItems"],
  },
  {
    permission: "platform:portal:admin:updateMemberCategorySchema",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:updateMemberCategorySchema"],
  },
  {
    permission: "platform:portal:admin:updateUsers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:updateUsers"],
  },
  {
    permission: "platform:portal:admin:viewGroups",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:viewGroups"],
  },
  {
    permission: "platform:portal:admin:viewItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:viewItems"],
  },
  {
    permission: "platform:portal:admin:viewUsers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:admin:viewUsers"],
  },
  {
    permission: "platform:portal:publisher:bulkPublishFromDataStores",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:bulkPublishFromDataStores"],
  },
  {
    permission: "platform:portal:publisher:createDataPipelines",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:createDataPipelines"],
  },
  {
    permission: "platform:portal:publisher:createFeatureWebhook",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:createFeatureWebhook"],
  },
  {
    permission: "platform:portal:publisher:publishBigDataAnalytics",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishBigDataAnalytics"],
  },
  {
    permission: "platform:portal:publisher:publishDynamicImagery",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishDynamicImagery"],
  },
  {
    permission: "platform:portal:publisher:publishFeatures",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishFeatures"],
  },
  {
    permission: "platform:portal:publisher:publishFeeds",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishFeeds"],
  },
  {
    permission: "platform:portal:publisher:publishKnowledgeGraph",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishKnowledgeGraph"],
  },
  {
    permission: "platform:portal:publisher:publishRealTimeAnalytics",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishRealTimeAnalytics"],
  },
  {
    permission: "platform:portal:publisher:publishScenes",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishScenes"],
  },
  {
    permission: "platform:portal:publisher:publishServerGPServices",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishServerGPServices"],
  },
  {
    permission: "platform:portal:publisher:publishServerServices",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishServerServices"],
  },
  {
    permission: "platform:portal:publisher:publishTiledImagery",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishTiledImagery"],
  },
  {
    permission: "platform:portal:publisher:publishTiles",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:publishTiles"],
  },
  {
    permission: "platform:portal:publisher:registerDataStores",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:publisher:registerDataStores"],
  },
  {
    permission: "platform:portal:user:addExternalMembersToGroup",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:addExternalMembersToGroup"],
  },
  {
    permission: "platform:portal:user:categorizeItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:categorizeItems"],
  },
  {
    permission: "platform:portal:user:createGroup",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:createGroup"],
  },
  {
    permission: "platform:portal:user:createItem",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:createItem"],
  },
  {
    permission: "platform:portal:user:invitePartneredCollaborationMembers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:invitePartneredCollaborationMembers"],
  },
  {
    permission: "platform:portal:user:joinGroup",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:joinGroup"],
  },
  {
    permission: "platform:portal:user:joinNonOrgGroup",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:joinNonOrgGroup"],
  },
  {
    permission: "platform:portal:user:reassignItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:reassignItems"],
  },
  {
    permission: "platform:portal:user:receiveItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:receiveItems"],
  },
  {
    permission: "platform:portal:user:runWebTool",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:runWebTool"],
  },
  {
    permission: "platform:portal:user:shareGroupToOrg",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:shareGroupToOrg"],
  },
  {
    permission: "platform:portal:user:shareGroupToPublic",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:shareGroupToPublic"],
  },
  {
    permission: "platform:portal:user:shareToGroup",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:shareToGroup"],
  },
  {
    permission: "platform:portal:user:shareToOrg",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:shareToOrg"],
  },
  {
    permission: "platform:portal:user:shareToPublic",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:shareToPublic"],
  },
  {
    permission: "platform:portal:user:viewHostedFeatureServices",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:viewHostedFeatureServices"],
  },
  {
    permission: "platform:portal:user:viewHostedTileServices",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:viewHostedTileServices"],
  },
  {
    permission: "platform:portal:user:viewOrgGroups",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:viewOrgGroups"],
  },
  {
    permission: "platform:portal:user:viewOrgItems",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:viewOrgItems"],
  },
  {
    permission: "platform:portal:user:viewOrgUsers",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:viewOrgUsers"],
  },
  {
    permission: "platform:portal:user:viewTracks",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["portal:user:viewTracks"],
  },
  {
    permission: "platform:premium:publisher:createAdvancedNotebooks",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:publisher:createAdvancedNotebooks"],
  },
  {
    permission: "platform:premium:publisher:createNotebooks",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:publisher:createNotebooks"],
  },
  {
    permission: "platform:premium:publisher:geoanalytics",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:publisher:geoanalytics"],
  },
  {
    permission: "platform:premium:publisher:rasteranalysis",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:publisher:rasteranalysis"],
  },
  {
    permission: "platform:premium:publisher:scheduleNotebooks",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:publisher:scheduleNotebooks"],
  },
  {
    permission: "platform:premium:user:demographics",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:demographics"],
  },
  {
    permission: "platform:premium:user:elevation",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:elevation"],
  },
  {
    permission: "platform:premium:user:featurereport",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:featurereport"],
  },
  {
    permission: "platform:premium:user:geocode:stored",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:geocode:stored"],
  },
  {
    permission: "platform:premium:user:geocode:temporary",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:geocode:temporary"],
  },
  {
    permission: "platform:premium:user:geocode",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:geocode"],
  },
  {
    permission: "platform:premium:user:geoenrichment",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:geoenrichment"],
  },
  {
    permission: "platform:premium:user:networkanalysis:closestfacility",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:closestfacility"],
  },
  {
    permission: "platform:premium:user:networkanalysis:locationallocation",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:locationallocation"],
  },
  {
    permission: "platform:premium:user:networkanalysis:optimizedrouting",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:optimizedrouting"],
  },
  {
    permission:
      "platform:premium:user:networkanalysis:origindestinationcostmatrix",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:origindestinationcostmatrix"],
  },
  {
    permission: "platform:premium:user:networkanalysis:routing",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:routing"],
  },
  {
    permission: "platform:premium:user:networkanalysis:servicearea",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:servicearea"],
  },
  {
    permission: "platform:premium:user:networkanalysis:vehiclerouting",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis:vehiclerouting"],
  },
  {
    permission: "platform:premium:user:networkanalysis",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:networkanalysis"],
  },
  {
    permission: "platform:premium:user:places",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:places"],
  },
  {
    permission: "platform:premium:user:spatialanalysis",
    subsystems: ["platform"],
    authenticated: true,
    privileges: ["premium:user:spatialanalysis"],
  },
];
