name: Deploy Documentation
# This is called from the release workflow so that the
# docs are updated and stamped with the version numbers 
# from the current release instead of the previous release
on:
  workflow_call:
   
  # push:
  #   branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: NPM Install
        run: npm install

      - name: Build Docs
        run: npm run docs:build

      - name: Deploy GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is supposed to work w/o specifying a token
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/hub.js
          CLEAN: false
