name: Build, Test, Release

# On pushes to master (i.e. merging a PR)
# run all tests, on win, macos, linux, on node 12 & 14
on:
  push:
    branches:
      - master
      - beta
      # - alpha disabled to allow push to alpha then merge to master w/o incurring a release
      - next
      - '[0-9]+.[0-9]+.x'
    # Dont run if it's just markdown or doc files
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  # First, build and test on multiple os's
  # and multuple versions of node
  build_and_test:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    # PRs will run tests on node 14,16 on ubuntu, macos and windows
    # so for the release, we're just running node 16@ubuntu
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      # npm ci was failing b/c package-lock.json was not in sync with package.json
      # copied this from publish-pr-preview.yaml
      - name: Setup npm v7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test in Chrome
        run: npm run test:chrome:ci

      - name: Test in Node
        run: npm run test:node

      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage

  # If the build and test works, run a release
  release:
    name: Release
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # This parameter is required to make sure sematic-relase exactly use the provided GitHub Token
          # See https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-a-master-branch
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 16.13

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup NPM auth
        run: |
          npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}
          npm whoami

      - name: Wait for NPM auth to propagate
        run: sleep 10

      - name: Release
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 4
          retry_wait_seconds: 45
          retry_on: error
          command: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.ESRI_DCDEV_SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-docs:
    name: 'Deploy Documentation'
    uses: ./.github/workflows/deploy-docs.yml
    needs:
      - release
