name: Build, Test, Release

# On pushes to master (i.e. merging a PR)
# run all tests, on win, macos, linux, on node 12 & 14
on:
  push:
    branches:
      - master
      - beta
    # Dont run if it's just markdown or doc files
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  # First, build and test on multiple os's
  # and multuple versions of node
  build_and_test:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    # PRs will run tests on node 14,16 on ubuntu, macos and windows
    # so for the release, we're just running node 16@ubuntu
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # Npm 7 is needed for workspaces, and it shipped w/ Node 16
      # But we want to test on downlevel versions of node so we
      # install npm7 directly
      - name: Npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test in Chrome
        run: npm run test:chrome:ci

      - name: Test in Node
        run: npm run test:node

      - uses: codecov/codecov-action@v1
        with:
          directory: ./coverage

  # If the build and test works, run a release
  release:
    name: Release
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13

      - name: Install and Build
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
