name: Build, Test, Release

# On pushes to master (i.e. merging a PR)
# run all tests, on win, macos, linux, on node versions
on:
  push:
    branches:
      - master
    # Dont run if it's just markdown or doc files
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  # First, build and test on multiple os's
  # and multuple versions of node
  build_and_test:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    # PRs will run tests on the following os/node combos
    # so for the release, we're just running node 18@ubuntu
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test in Chrome
        run: npm run test:chrome:ci

      - name: Test in Node
        run: npm run test:node

      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage

  # If the build and test works, run a release
  release:
    name: Release
    needs: [build_and_test]
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm ci

      # - name: Setup NPM auth
      #   run: |
      #     npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}
      #     npm whoami

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # ci:release does a build and calls changeset publish
          publish: npm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Tom is the owner of the current token
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-docs:
    name: 'Deploy Documentation'
    uses: ./.github/workflows/deploy-docs.yml
    needs:
      - release
