import { ISearchResult } from "@esri/arcgis-rest-items";

export const adminEventSearchResponse: any = {
  query:
    "typekeywords:hubEventsLayer AND orgid:5bc  NOT id:a6ae3d1aa19548b89546c7d3b0ed246f",
  total: 3,
  start: 1,
  num: 10,
  nextStart: -1,
  results: [
    {
      id: "d545001102994aad860f2037d9796fec",
      owner: "dcadminqa",
      created: 1498571469000,
      modified: 1533053014000,
      guid: null,
      name: "Hub Events",
      title: "Hub Events",
      type: "Feature Service",
      typeKeywords: [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "hubEventsLayer",
        "Service",
        "Singlelayer",
        "Hosted Service"
      ],
      description:
        "Feature service generated by Hub for Hub events. DO NOT DELETE THIS SERVICE. It stores the Hub events for your organization.",
      tags: [],
      snippet: "Feature service for Hub events",
      thumbnail: "thumbnail/ago_downloaded.png",
      documentation: null,
      extent: [
        [-8589300.590117617, 40.36926825227528],
        [-73.96624645399964, 4722244.554455302]
      ],
      categories: [],
      spatialReference: "null",
      accessInformation: "null",
      licenseInfo: "null",
      culture: "en-us",
      properties: {
        schemaVersion: "2.0"
      },
      url:
        "https://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/Hub Events/FeatureServer",
      proxyFilter: null,
      access: "shared",
      size: -1,
      appCategories: [],
      industries: [],
      languages: [],
      largeThumbnail: null,
      banner: null,
      screenshots: [],
      listed: false,
      numComments: 0,
      numRatings: 0,
      avgRating: 0,
      numViews: 86,
      scoreCompleteness: 68,
      groupDesignations: null
    },
    {
      id: "d2c691f4847548fdad2fbcd4e3c42f36",
      owner: "dcadminqa",
      created: 1498571478000,
      modified: 1533053018000,
      guid: null,
      name: "Hub Events (org)",
      title: "Hub Events (org)",
      type: "Feature Service",
      typeKeywords: [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "hubEventsLayer",
        "Service",
        "Singlelayer",
        "Hosted Service",
        "View Service"
      ],
      description:
        "Feature service generated by Hub for organization Hub events. DO NOT DELETE THIS SERVICE. It stores the organization Hub events for your organization.",
      tags: [],
      snippet: "Feature service for organization Hub events",
      thumbnail: "thumbnail/ago_downloaded.png",
      documentation: null,
      extent: [
        [-8589300.590117617, 40.36926825227528],
        [-73.96624645399964, 4722244.554455302]
      ],
      categories: [],
      spatialReference: "null",
      accessInformation: "null",
      licenseInfo: "null",
      culture: null,
      properties: {
        schemaVersion: "2.0"
      },
      url:
        "https://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/Hub Events (org)/FeatureServer",
      proxyFilter: null,
      access: "org",
      size: -1,
      appCategories: [],
      industries: [],
      languages: [],
      largeThumbnail: null,
      banner: null,
      screenshots: [],
      listed: false,
      numComments: 0,
      numRatings: 0,
      avgRating: 0,
      numViews: 10,
      scoreCompleteness: 70,
      groupDesignations: null
    },
    {
      id: "04e475b83b8a4f0e885fc8bffacfa3b6",
      owner: "dcadminqa",
      created: 1498571489000,
      modified: 1533053016000,
      guid: null,
      name: "Hub Events (public)",
      title: "Hub Events (public)",
      type: "Feature Service",
      typeKeywords: [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "hubEventsLayer",
        "Service",
        "Singlelayer",
        "Hosted Service",
        "View Service"
      ],
      description:
        "Feature service generated by Hub for public Hub events. DO NOT DELETE THIS SERVICE. It stores the public Hub events for your organization.",
      tags: [],
      snippet: "Feature service for public Hub events",
      thumbnail: "thumbnail/ago_downloaded.png",
      documentation: null,
      extent: [
        [-8589300.590117617, 40.36926825227528],
        [-73.96624645399964, 4722244.554455302]
      ],
      categories: [],
      spatialReference: "null",
      accessInformation: "null",
      licenseInfo: "null",
      culture: null,
      properties: {
        schemaVersion: "2.0"
      },
      url:
        "https://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/Hub Events (public)/FeatureServer",
      proxyFilter: null,
      access: "public",
      size: -1,
      appCategories: [],
      industries: [],
      languages: [],
      largeThumbnail: null,
      banner: null,
      screenshots: [],
      listed: false,
      numComments: 0,
      numRatings: 0,
      avgRating: 0,
      numViews: 21,
      scoreCompleteness: 70,
      groupDesignations: null
    }
  ]
};

export const orgEventSearchResponse: any = {
  query:
    "typekeywords:hubEventsLayer AND orgid:5bc  NOT id:a6ae3d1aa19548b89546c7d3b0ed246f",
  total: 2,
  start: 1,
  num: 10,
  nextStart: -1,
  results: [
    {
      id: "d2c691f4847548fdad2fbcd4e3c42f36",
      owner: "dcadminqa",
      created: 1498571478000,
      modified: 1533053018000,
      guid: null,
      name: "Hub Events (org)",
      title: "Hub Events (org)",
      type: "Feature Service",
      typeKeywords: [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "hubEventsLayer",
        "Service",
        "Singlelayer",
        "Hosted Service",
        "View Service"
      ],
      description:
        "Feature service generated by Hub for organization Hub events. DO NOT DELETE THIS SERVICE. It stores the organization Hub events for your organization.",
      tags: [],
      snippet: "Feature service for organization Hub events",
      thumbnail: "thumbnail/ago_downloaded.png",
      documentation: null,
      extent: [
        [-8589300.590117617, 40.36926825227528],
        [-73.96624645399964, 4722244.554455302]
      ],
      categories: [],
      spatialReference: "null",
      accessInformation: "null",
      licenseInfo: "null",
      culture: null,
      properties: {
        schemaVersion: "2.0"
      },
      url:
        "https://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/Hub Events (org)/FeatureServer",
      proxyFilter: null,
      access: "org",
      size: -1,
      appCategories: [],
      industries: [],
      languages: [],
      largeThumbnail: null,
      banner: null,
      screenshots: [],
      listed: false,
      numComments: 0,
      numRatings: 0,
      avgRating: 0,
      numViews: 10,
      scoreCompleteness: 70,
      groupDesignations: null
    },
    {
      id: "04e475b83b8a4f0e885fc8bffacfa3b6",
      owner: "dcadminqa",
      created: 1498571489000,
      modified: 1533053016000,
      guid: null,
      name: "Hub Events (public)",
      title: "Hub Events (public)",
      type: "Feature Service",
      typeKeywords: [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "hubEventsLayer",
        "Service",
        "Singlelayer",
        "Hosted Service",
        "View Service"
      ],
      description:
        "Feature service generated by Hub for public Hub events. DO NOT DELETE THIS SERVICE. It stores the public Hub events for your organization.",
      tags: [],
      snippet: "Feature service for public Hub events",
      thumbnail: "thumbnail/ago_downloaded.png",
      documentation: null,
      extent: [
        [-8589300.590117617, 40.36926825227528],
        [-73.96624645399964, 4722244.554455302]
      ],
      categories: [],
      spatialReference: "null",
      accessInformation: "null",
      licenseInfo: "null",
      culture: null,
      properties: {
        schemaVersion: "2.0"
      },
      url:
        "https://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/Hub Events (public)/FeatureServer",
      proxyFilter: null,
      access: "public",
      size: -1,
      appCategories: [],
      industries: [],
      languages: [],
      largeThumbnail: null,
      banner: null,
      screenshots: [],
      listed: false,
      numComments: 0,
      numRatings: 0,
      avgRating: 0,
      numViews: 21,
      scoreCompleteness: 70,
      groupDesignations: null
    }
  ]
};

export const publicEventSearchResponse: any = {
  query:
    "typekeywords:hubEventsLayer AND orgid:5bc  NOT id:a6ae3d1aa19548b89546c7d3b0ed246f",
  total: 1,
  start: 1,
  num: 10,
  nextStart: -1,
  results: [
    {
      id: "04e475b83b8a4f0e885fc8bffacfa3b6",
      owner: "dcadminqa",
      created: 1498571489000,
      modified: 1533053016000,
      guid: null,
      name: "Hub Events (public)",
      title: "Hub Events (public)",
      type: "Feature Service",
      typeKeywords: [
        "ArcGIS Server",
        "Data",
        "Feature Access",
        "Feature Service",
        "hubEventsLayer",
        "Service",
        "Singlelayer",
        "Hosted Service",
        "View Service"
      ],
      description:
        "Feature service generated by Hub for public Hub events. DO NOT DELETE THIS SERVICE. It stores the public Hub events for your organization.",
      tags: [],
      snippet: "Feature service for public Hub events",
      thumbnail: "thumbnail/ago_downloaded.png",
      documentation: null,
      extent: [
        [-8589300.590117617, 40.36926825227528],
        [-73.96624645399964, 4722244.554455302]
      ],
      categories: [],
      spatialReference: "null",
      accessInformation: "null",
      licenseInfo: "null",
      culture: null,
      properties: {
        schemaVersion: "2.0"
      },
      url:
        "https://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/Hub Events (public)/FeatureServer",
      proxyFilter: null,
      access: "public",
      size: -1,
      appCategories: [],
      industries: [],
      languages: [],
      largeThumbnail: null,
      banner: null,
      screenshots: [],
      listed: false,
      numComments: 0,
      numRatings: 0,
      avgRating: 0,
      numViews: 21,
      scoreCompleteness: 70,
      groupDesignations: null
    }
  ]
};

export const emptyEventSearchResponse: ISearchResult = {
  query: "hubEventsLayer AND orgid:h7c",
  total: 1,
  start: 1,
  num: 10,
  nextStart: -1,
  results: []
};
